GET http://localhost:2000/products
###
PATCH  http://localhost:2000/carts
Content-Type: application/json

{
"id":"61818f289500713567cf5a6d",
"price":4000,
"sale":10,
"finalPrice":3600
}
###
PATCH   http://localhost:2000/carts/61896040a4e1bc8796a85a26
###
POST   http://localhost:2000/addProduct